version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: gerenciador-versoes-db
    environment:
      POSTGRES_DB: gerenciador_versoes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - gerenciador-network

  # Aplicação Quarkus
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: gerenciador-versoes-app
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/gerenciador_versoes
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - gerenciador-network
    restart: unless-stopped

  # Admin do PostgreSQL (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gerenciador-versoes-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - gerenciador-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  gerenciador-network:
    driver: bridge
